apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: update-index
spec:
  concurrencyPolicy: Forbid
  schedule: "0 0 * * 0"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        {{- include "indexing-job-template" . | nindent 8 }}
         
