apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: elastic-recherche-entreprises-read
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    ELASTICSEARCH_URL: >-
      AgCxK1MqqVkCOHvMjjcieUsj1uE/ATUzAfYTYVEMqcWFxTnugOaYlXB2mTuZtzdjXNvINREzDynnVRBghPIJvrJm59vPgexC5FyQptdPf2XwQAG6n0yMLWAEBM+O8ieO1D6vBu6BYuq4QYoItq+SMTE6APNX+p6wi4/LP04cR8p8bVKNxckPMfyVfQGhUSTD+2gC5ow2x1Mx67odqqP3E8eK9tm5tU6ltzOpKqJKITUQIqTQbSKFr8p77DE4IrdbPn8MpvdP+VrT+ztF4thPkpVpuYWy9rABdQKeEuNdN2AuvmPeJs/2B80iApIgtWWQjV/iG+WlLGMohvWDZVsBGuBuYGzhjJlr5w8OljwKDihb2cG1M/Ot/LM1xRuCC85wvqH0oMhnnP/3DZts5aYAN+qjAezOkPT9kjT+gu0WoQB+E5r9ITcYYHYbJw/YSxS2z86Ul0amRRW4ovAWT5c/nFDZU6i74I8YyVh8oOtrieZgNF4ajJcIr5YpjT2LICKoZR0KExrQ4V30zZJ+wZcvd8W3e/KCmKsFxloTkLq/sjEiFQoe6ffYTQhSUXZynqrdUKZsdoSleprfctlJtf3rzxt5hZIpcLulXrYk7pPPiHkTcV3Zc4zkN3BFE1A9vsgTvh6xTXlvUekJHHMXU3t8ZyZD8vvemxv0FE8G33XWQF2DEkmyc3gXMlfPDLho4fHv0h0iId0c9klFkOpmp8REFWJyuRQjq+hOHvfoCSu1ymsCwA0CMAguJoX1XEhn0aA9QIgf0VyBe/cVJwu/GfW74UBi6x5feqzFovYIUXbDP6kW
    ELASTICSEARCH_API_KEY: >-
      AgBO5D0q5m4SpJwfAgNM3cqLYYuFQGai28AKvulmD5bCgoLOFRJNhP0K4v3wsqb4OwQwSf+VJG4ACNvD0aqJhDATIZw3RRu3GODXnWXQhoiYXzjYOovZYSDLtPQBVOMwvb0oMXK5ZR92UqXop2A3i9m82uormFtVwn/+7rMFCT70Nm6NGg5gjEmi1eZeK1JImpk9VJm51zFVnAQEwgo84qLwTWAQ0OyekOrrnrbSD7cji57z1gPG/uculnRkqvlcJQjFwFkp02JIhNG3+6v6YgYHRt49YjJ4iz4xGx4FHMcZNSGgyzAO2VyBnTOLwHV+oTxxHDGf4PoL89sgX5fpRLX42MbbjGQwJLccno2Nn1Kzal8yTEjkGn12RDS70c4ieqP9puzmaMIH6+yHowA+dDjlIRqP2cmfPgC6cCEuzssdSm52ME6zdIQj/0xgcHVOEJJkltBPQuM/5k0oFtiiPYAFWxgIDEYH5WXMKRaTYUsV2BEqAC7KeiO4rFFmHQLW1F/6Rs64eHbsCLrJ+81mh52nuRdbg8G4OhP4550lVWRB5eOp4SeAO3b593QQ2pLV/m6Gy5kE1G9yOp2Ac6hceO115jMeEWeJ2+9Rn2MRNZQVunt4Fv7hE65uKWc4+UhYiWw/fjkNpZh4s2XG6Xl26IBMaPrRblQFI+PzVHRm8r82F7DOaWvmr/MUZMpn1nLykNAyumvGbQJEtBYG+QnFTw7slascjnuGcCEnaPcacjP2FF2IV+RzRKQjyEWxb9UOXuJgd9v0ewBJOVCZpLM=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: elastic-recherche-entreprises-read
    type: Opaque
