front:
  host: recherche-entreprises-preprod.dev.fabrique.social.gouv.fr

api:
  replicas: 2
  host: api-recherche-entreprises-preprod.dev.fabrique.social.gouv.fr

jobs:
  runs:
    build-front:
      with:
        imagePackage: front
        context: front
        buildArgs:
          REACT_APP_API_URL: https://api-recherche-entreprises-preprod.dev.fabrique.social.gouv.fr/api/v1