front:
  ~chart: app
  imagePackage: front
  containerPort: 8080

api:
  ~chart: app
  imagePackage: api
  host: "api-{{ .Values.global.host }}"
  envFrom:
    - secretRef:
        name: elastic-recherche-entreprises-read
