name: 🇫🇷

on:
  pull_request:
    types: [closed]

jobs:
  bury_review_env:
    name: 🪦 Review
    runs-on: ubuntu-latest
    steps:
      - uses: SocialGouv/actions/autodevops-deactivate@V1
        with:
          kube-config: ${{ secrets.KUBECONFIG }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
