name: Indexing (prod)

on:
  workflow_dispatch:
  schedule: 
    - cron:  '30 0 * * 0'
    
concurrency:
  cancel-in-progress: true
  group: indexing-prod

jobs:
  index:
    name: Index Prod
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://recherche-entreprises.fabrique.social.gouv.fr
    steps:
      - uses: SocialGouv/kube-workflow@v1
        with:
          environment: prod
          charts: indexing-job
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
