name: #️⃣ Indexing (prod)

on:
  workflow_dispatch:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.event.ref }}

jobs:
  indexing-job:
    name: "#️⃣ Indexing prod"
    uses: socialgouv/workflows/.github/workflows/use-ks-gh-manual.yaml@v1
    secrets: inherit
    with:
      environment: prod
      charts: indexing-job
