name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGE
  ##############################################################################
  register:
    name: Build & Register docker images
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Register API
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          project: ${{ env.project }}
          imageName: ${{ env.project }}/api
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./api/Dockerfile
          dockercontext: ./api

      - name: Register Frontend (demo)
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          project: ${{ env.project }}
          imageName: ${{ env.project }}/front
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./front/Dockerfile
          dockercontext: ./front
          dockerbuildargs: |
            REACT_APP_API_URL=https://api.recherche-entreprises.fabrique.social.gouv.fr/api/v1

      - name: Register Indexing
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          environment: prod
          project: ${{ env.project }}
          imageName: ${{ env.project }}/index
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./index/Dockerfile
          dockercontext: ./index

  ##############################################################################
  ## DEPLOY PRODUCTION APPLICATION
  ##############################################################################
  deploy-prod:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: [register]
    environment:
      name: production
      url: https://recherche-entreprises.fabrique.social.gouv.fr
    steps:
      - uses: SocialGouv/kube-workflow@v1
        with:
          environment: prod
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
