name: Review

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          echo "project=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV

      - name: Register API
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/search
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./api/Dockerfile
          dockercontext: ./api

      - name: Register Frontend (demo)
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/front
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./front/Dockerfile
          dockercontext: ./front

      - name: Register Indexing
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/index
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./index/Dockerfile
          dockercontext: ./index

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register, manifests]
    steps:
      - uses: SocialGouv/kube-workflow@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
