name: Review

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: ${{ github.ref }}

jobs:
  ##############################################################################
  ## BUILD AND REGISTER DOCKER IMAGES
  ##############################################################################
  register:
    name: Build & Register
    runs-on: ubuntu-latest
    steps:
      - name: Get project name
        run: |
          REPOSITORY=${GITHUB_REPOSITORY#*/}
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          HOST=$(npx kube-workflow slugify $REPOSITORY-$BRANCH)
          echo $REPOSITORY
          echo $BRANCH
          echo $HOST

          echo "project=${REPOSITORY}" >> $GITHUB_ENV
          echo "branch=${BRANCH}" >> $GITHUB_ENV
          echo "host=${HOST}" >> $GITHUB_ENV

      - name: Register API
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/api
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./api/Dockerfile
          dockercontext: ./api

      - name: Register Frontend (demo)
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/front
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./front/Dockerfile
          dockercontext: ./front
          dockerbuildargs: |
            REACT_APP_API_URL=https://api-${{ env.host }}.dev.fabrique.social.gouv.fr/api/v1

      - name: Register Indexing
        uses: SocialGouv/actions/autodevops-build-register@v1
        with:
          project: ${{ env.project }}
          imageName: ${{ env.project }}/index
          token: ${{ secrets.GITHUB_TOKEN }}
          dockerfile: ./index/Dockerfile
          dockercontext: ./index

  ##############################################################################
  ## DEPLOY APPLICATION OVER KUBERNETES
  ##############################################################################
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [register]
    steps:
      - uses: SocialGouv/kube-workflow@v1
        with:
          environment: dev
          token: ${{ secrets.GITHUB_TOKEN }}
          kubeconfig: ${{ secrets.KUBECONFIG }}
          rancherProjectId: ${{ secrets.RANCHER_PROJECT_ID }}
          rancherProjectName: ${{ secrets.RANCHER_PROJECT_NAME }}
